language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt

script:
    coverage run --source='./codefett/' ./codefett/manage.py test

after_success:
    - coverage report 
    - coveralls
