language: python

python:
    - 3.6

install:
    - pip install -r requirements/requirements_dev.txt

script:
    cd codefett && coverage run --source='.' ./manage.py test

after_success:
    - coverage report 
    - coveralls 
